### ISSUE TITLE
negative analogWrite

### ISSUE THREAD

**Issue by karmanyaahm** [tysweat/arduino-L293D#2]
Hello, thanks for this great library.
I'm running into a bug which can be fixed by multiplying the value by -1 in analogWrite because that only takes in positive numbers.

https://github.com/tylersweat/arduino-L293D/blob/6bf7a332ce09c47fe336a840ead7fe05c268bf42/L293D.cpp#L55-L59

**Comment by tylersweat** [comment]
Can you provide more details on what is causing the bug and how multiplying by negative one helps? Once I know what the underlying issue is I can fix it or you can for the repo and fix it then send a pull request

**Comment by karmanyaahm** [comment]
The Arduino documentation [here](https://www.arduino.cc/reference/en/language/functions/analog-io/analogwrite/) says
>  value: the duty cycle: between 0 (always off) and 255 (always on). Allowed data types: int.

When I input something like -0.33 into the motor control the PWM voltage I get out is ~3.5volts when it should be 1.66V because as far as I can tell the underlying implementation assumes it's an unsigned int and processes it accordingly.
